#!/bin/sh

########################################################################

if [ -d html ]
then 
    echo "\tcleaning html files"
    rm -fr html 
fi


########################################################################

if [ -d latex ]
then 
    echo "\tcleaning latex files"
    rm -fr latex 
fi


########################################################################

if [ -d xml ]
then 
    echo "\tcleaning xml files"
    rm -fr xml 
fi


########################################################################

if [ -f spct_tags.doc ]
then 
    rm -f spct_tags.doc
fi


########################################################################


rm -f  *~
