#!/bin/sh

echo ""

########################################################################

echo "cleaning cmake files"

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f Makefile ]
then 
    rm -f Makefile
fi


########################################################################
# Add plug-in directories here if they have a 'clean_files' script, 
# see the templates directory for examples
########################################################################

echo "--cleaning audio--"

cd ./audio/
./clean_files
cd ..


########################################################################

echo "--cleaning cost_functions--"

cd ./cost_functions/
./clean_files
cd ..


########################################################################

echo "--cleaning unit_db--"

cd ./unit_db/
./clean_files
cd ..


########################################################################

echo "--cleaning wave_generation--"

cd ./wave_generation/
./clean_files
cd ..


########################################################################

echo "--cleaning window_functions--"

cd ./window_functions/
./clean_files
cd ..


########################################################################


rm -f  *~

echo ""
