#!/bin/sh

echo "\t\tin base"


########################################################################

echo "\t\tcleaning errdbg"
cd ./errdbg/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning objsystem"
cd ./objsystem/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning strings"
cd ./strings/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning utils"
cd ./utils/
./clean_files
cd ..


########################################################################


rm -f *~
rm -fr CMakeFiles
rm -f cmake_install.cmake
rm -f Makefile
