#!/bin/sh

echo "in engine"

########################################################################

if [ -f Makefile ]
then 
    echo "running make clean"
    make clean
    rm -f  Makefile 
fi

########################################################################

echo "cleaning cmake files"

if [ -f CMakeCache.txt ]
then 
    rm -f  CMakeCache.txt 
fi

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f CTestTestfile.cmake ]
then 
    rm -f CTestTestfile.cmake
fi


########################################################################

echo "cleaning cmake"

cd ./cmake/
./clean_files
cd ..


########################################################################

echo "cleaning config"

cd ./config/
./clean_files
cd ..


########################################################################

echo "cleaning examples"

cd ./examples/
./clean_files
cd ..


########################################################################

echo "cleaning lib"

cd ./lib/
./clean_files
cd ..


########################################################################

echo "cleaning src"

cd ./src/
./clean_files
cd ..


########################################################################

echo "cleaning swig"

cd ./swig/
./clean_files
cd ..


########################################################################

echo "cleaning tests"

cd ./tests/
./clean_files
cd ..


########################################################################

rm -f  *~

echo ""
