#!/bin/sh

echo ""

########################################################################

if [ -f Makefile ]
then 
    echo "running make clean"
    make clean
    rm -f  Makefile 
fi

########################################################################

echo "cleaning cmake files"

if [ -f CMakeCache.txt ]
then 
    rm -f  CMakeCache.txt 
fi

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f cmake_uninstall.cmake ]
then 
    rm -f cmake_uninstall.cmake
fi

if [ -f CTestTestfile.cmake ]
then 
    rm -f CTestTestfile.cmake
fi

if [ -f install_manifest.txt ]
then 
    rm -f install_manifest.txt
fi

if [ -f spctConfig.cmake ]
then 
    rm -f spctConfig.cmake
fi

if [ -f SpeectConf.cmake ]
then 
    rm -f SpeectConf.cmake
fi

if [ -f speect.conf ]
then 
    rm -f speect.conf
fi

if [ -f spct_debug.log ]
then 
    rm -f spct_debug.log
fi

if [ -f spct_error.log ]
then 
    rm -f spct_error.log
fi


########################################################################

echo "cleaning cmake"

cd ./cmake/
./clean_files
cd ..


########################################################################

echo "cleaning config"

cd ./config/
./clean_files
cd ..


########################################################################

echo "cleaning examples"

cd ./examples/
./clean_files
cd ..


########################################################################

echo "cleaning lib"

cd ./lib/
./clean_files
cd ..


########################################################################

echo "cleaning src"

cd ./src/
./clean_files
cd ..


########################################################################

echo "cleaning swig"

cd ./swig/
./clean_files
cd ..


########################################################################

echo "cleaning tests"

cd ./tests/
./clean_files
cd ..


########################################################################

rm -f  *~

echo ""
