#!/bin/sh

echo "\t\tin pluginmamanger"


########################################################################

echo "\t\tcleaning platform"
cd ./platform/
./clean_files
cd ..


########################################################################

rm -f  *~
