#!/bin/sh

echo "\t\t\tin containers"


########################################################################

echo "\t\t\tcleaning buffer"
cd ./buffer/
./clean_files
cd ..


########################################################################

echo "\t\t\tcleaning hashtable"
cd ./hashtable/
./clean_files
cd ..


########################################################################

echo "\t\t\tcleaning list"
cd ./list/
./clean_files
cd ..


########################################################################


rm -f  *~
