#!/bin/sh

echo "\t\tin base"


########################################################################

echo "\t\tcleaning containers"
cd ./containers/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning errdbg"
cd ./errdbg/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning iniparser"
cd ./iniparser/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning log"
cd ./log/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning objsystem"
cd ./objsystem/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning strings"
cd ./strings/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning threads"
cd ./threads/
./clean_files
cd ..


########################################################################

echo "\t\tcleaning utils"
cd ./utils/
./clean_files
cd ..


########################################################################


rm -f  *~
