#!/bin/sh

echo "\tin python"

########################################################################

echo "\tcleaning cmake"

cd ./cmake/
./clean_files
cd ..


########################################################################

echo "\tcleaning config"

cd ./config/
./clean_files
cd ..


########################################################################

echo "\tcleaning examples"

cd ./examples/
./clean_files
cd ..


########################################################################

echo "\tcleaning speect"

cd ./speect/
./clean_files
cd ..


########################################################################

echo "\tcleaning tools"

cd ./tools/
./clean_files
cd ..


########################################################################

rm -f  *~
rm -f *.pyc
rm -f *.so