#!/bin/sh

echo "in swig"


########################################################################

echo "cleaning cmake"
cd ./cmake/
./clean_files
cd ..


########################################################################

echo "cleaning python"
cd ./python/
./clean_files
cd ..


########################################################################

rm -f *~
rm -fr CMakeFiles
rm -f CMakeCache.txt
rm -f cmake_install.cmake
rm -f Makefile

