#!/bin/sh

echo ""

########################################################################

echo "cleaning cmake files"

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f Makefile ]
then 
    rm -f Makefile
fi


########################################################################
# Add plug-in directories here if they have a 'clean_files' script, 
# see the templates directory for examples
########################################################################

echo "--cleaning simple1"

cd ./simple1/
./clean_files
cd ..


########################################################################

echo "--cleaning simple2"

cd ./simple2/
./clean_files
cd ..


########################################################################

echo "--cleaning simple3"

cd ./simple3/
./clean_files
cd ..


########################################################################

echo "--cleaning simple4"

cd ./simple4/
./clean_files
cd ..


########################################################################

echo "--cleaning simple5"

cd ./simple5/
./clean_files
cd ..


########################################################################


rm -f  *~

echo ""
