#!/bin/sh

echo ""

########################################################################

echo "cleaning cmake files"

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f Makefile ]
then 
    rm -f Makefile
fi


########################################################################
# Add plug-in directories here if they have a 'clean_files' script, 
# see the templates directory for examples
########################################################################

echo "--cleaning left_context--"

cd ./left_context/
./clean_files
cd ..


########################################################################

echo "--cleaning num_syls--"

cd ./num_syls/
./clean_files
cd ..


########################################################################

echo "--cleaning right_context--"

cd ./right_context/
./clean_files
cd ..


########################################################################

echo "--cleaning syl_pos--"

cd ./syl_pos/
./clean_files
cd ..


########################################################################

echo "--cleaning word_pos--"

cd ./word_pos/
./clean_files
cd ..


########################################################################


rm -f  *~

echo ""
