#!/bin/sh

echo "\t\t\tin native"


########################################################################

if [ -f Makefile ]
then 
    echo "\t\t\trunning make clean"
    make clean
    rm -f  Makefile 
fi

########################################################################

echo "\t\t\tcleaning cmake files"

if [ -f CMakeCache.txt ]
then 
    rm -f  CMakeCache.txt 
fi

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f cmake_uninstall.cmake ]
then 
    rm -f cmake_uninstall.cmake
fi

if [ -f CTestTestfile.cmake ]
then 
    rm -f CTestTestfile.cmake
fi

if [ -f install_manifest.txt ]
then 
    rm -f install_manifest.txt
fi


########################################################################

echo "\t\t\tcleaning examples"

cd ./examples/
./clean_files
cd ..


########################################################################

rm -f *~

