#!/bin/sh

########################################################################

echo "\tcleaning cmake files"

rm -f  CMakeCache.txt 
rm -fr CMakeFiles 
rm -f  cmake_install.cmake
rm -f  Makefile


########################################################################

rm -f *~