#!/bin/sh

echo ""

########################################################################

echo "cleaning cmake files"

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f Makefile ]
then 
    rm -f Makefile
fi


########################################################################
# Add plug-in directories here if they have a 'clean_files' script, 
# see the templates directory for examples
########################################################################

echo "--cleaning segment_duration--"

cd ./segment_duration/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_end--"

cd ./segment_end/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_mid--"

cd ./segment_mid/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_name_multilingual--"

cd ./segment_name_multilingual/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_pos_syl--"

cd ./segment_pos_syl/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_pos_syl_rev--"

cd ./segment_pos_syl_rev/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_phoneset_feature--"

cd ./segment_phoneset_feature/
./clean_files
cd ..


########################################################################

echo "--cleaning segment_start--"

cd ./segment_start/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_break--"

cd ./syllable_break/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_duration--"

cd ./syllable_duration/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_end--"

cd ./syllable_end/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_num_phones--"

cd ./syllable_num_phones/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_pos_type--"

cd ./syllable_pos_type/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_pos_word--"

cd ./syllable_pos_word/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_pos_word_rev--"

cd ./syllable_pos_word_rev/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_pos_phrase--"

cd ./syllable_pos_phrase/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_pos_phrase_rev--"

cd ./syllable_pos_phrase_rev/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_start--"

cd ./syllable_start/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_vowel--"

cd ./syllable_vowel/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_stress_in--"

cd ./syllable_stress_in/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_stress_out--"

cd ./syllable_stress_out/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_accent_in--"

cd ./syllable_accent_in/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_accent_out--"

cd ./syllable_accent_out/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_stress_all_in--"

cd ./syllable_stress_all_in/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_stress_all_out--"

cd ./syllable_stress_all_out/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_accent_all_in--"

cd ./syllable_accent_all_in/
./clean_files
cd ..


########################################################################

echo "--cleaning syllable_accent_all_out--"

cd ./syllable_accent_all_out/
./clean_files
cd ..


########################################################################

echo "--cleaning word_break--"

cd ./word_break/
./clean_files
cd ..


########################################################################

echo "--cleaning word_duration--"

cd ./word_duration/
./clean_files
cd ..


########################################################################

echo "--cleaning word_end--"

cd ./word_end/
./clean_files
cd ..


########################################################################

echo "--cleaning word_num_syls--"

cd ./word_num_syls/
./clean_files
cd ..


########################################################################

echo "--cleaning word_pos_phrase--"

cd ./word_pos_phrase/
./clean_files
cd ..


########################################################################

echo "--cleaning word_pos_phrase_rev--"

cd ./word_pos_phrase_rev/
./clean_files
cd ..


########################################################################

echo "--cleaning word_start--"

cd ./word_start/
./clean_files
cd ..


########################################################################

echo "--cleaning word_content_in--"

cd ./word_content_in/
./clean_files
cd ..


########################################################################

echo "--cleaning word_content_out--"

cd ./word_content_out/
./clean_files
cd ..


########################################################################

echo "--cleaning word_content_all_in--"

cd ./word_content_all_in/
./clean_files
cd ..


########################################################################

echo "--cleaning word_content_all_out--"

cd ./word_content_all_out/
./clean_files
cd ..


########################################################################

echo "--cleaning phrase_num_syls--"

cd ./phrase_num_syls/
./clean_files
cd ..


########################################################################

echo "--cleaning phrase_num_words--"

cd ./phrase_num_words/
./clean_files
cd ..


########################################################################

echo "--cleaning phrase_pos_utt--"

cd ./phrase_pos_utt/
./clean_files
cd ..


########################################################################

echo "--cleaning phrase_pos_utt_rev--"

cd ./phrase_pos_utt_rev/
./clean_files
cd ..


########################################################################

echo "--cleaning utt_num_syls--"

cd ./utt_num_syls/
./clean_files
cd ..


########################################################################

echo "--cleaning utt_num_words--"

cd ./utt_num_words/
./clean_files
cd ..


########################################################################

echo "--cleaning utt_num_phrases--"

cd ./utt_num_phrases/
./clean_files
cd ..


########################################################################

echo "--cleaning hts_labels--"

cd ./hts_labels/
./clean_files
cd ..


########################################################################


rm -f  *~

echo ""
