#!/bin/sh

echo "\t\tin speect"

########################################################################

echo "\t\tcleaning modules"

cd ./modules/
./clean_files
cd ..


########################################################################

rm -f  *~
rm -f *.pyc
rm -f *.so