#!/bin/sh

echo "\tin swig"


########################################################################

echo "\tcleaning python"
cd ./python/
./clean_files
cd ..


########################################################################

echo "\tcleaning common"
cd ./common/
./clean_files
cd ..


########################################################################

rm -f *~
rm -fr CMakeFiles
rm -f CMakeCache.txt
rm -f cmake_install.cmake
rm -f Makefile

