#!/bin/sh

echo ""

########################################################################

echo "cleaning cmake files"

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f Makefile ]
then 
    rm -f Makefile
fi


########################################################################
# Add plug-in directories here if they have a 'clean_files' script, 
# see the templates directory for examples
########################################################################

echo "--cleaning lexlookup--"

cd ./lexlookup/
./clean_files
cd ..


########################################################################

echo "--cleaning normalizer--"

cd ./normalizer/
./clean_files
cd ..


########################################################################

echo "--cleaning pauses--"

cd ./pauses/
./clean_files
cd ..


########################################################################

echo "--cleaning phrasify--"

cd ./phrasify/
./clean_files
cd ..


########################################################################

echo "--cleaning tokenizer--"

cd ./tokenizer/
./clean_files
cd ..


########################################################################

echo "--cleaning syltone--"

cd ./syltone/
./clean_files
cd ..


########################################################################

echo "--cleaning morphdecomp--"

cd ./morphdecomp/
./clean_files
cd ..


########################################################################


rm -f  *~

echo ""
