#!/bin/sh

echo ""

########################################################################

echo "cleaning cmake files"

if [ -d CMakeFiles ]
then 
    rm -fr CMakeFiles
fi

if [ -f cmake_install.cmake ]
then 
    rm -f cmake_install.cmake
fi

if [ -f Makefile ]
then 
    rm -f Makefile
fi


########################################################################
# Add plug-in directories here if they have a 'clean_files' script, 
# see the templates directory for examples
########################################################################

echo "--cleaning addendum--"

cd ./addendum/
./clean_files
cd ..


########################################################################

echo "--cleaning cost_functions--"

cd ./cost_functions/
./clean_files
cd ..


########################################################################

echo "--cleaning g2p--"

cd ./g2p/
./clean_files
cd ..


########################################################################

echo "--cleaning lexicon--"

cd ./lexicon/
./clean_files
cd ..


########################################################################

echo "--cleaning phoneset--"

cd ./phoneset/
./clean_files
cd ..


########################################################################

echo "--cleaning syllabification--"

cd ./syllabification/
./clean_files
cd ..


########################################################################


rm -f  *~

echo ""
